### PR TITLE
Fix types for all fields

### PR DESCRIPTION
**Pull request by Bigfootjon**

### CODE REVIEW

**Comment by Bigfootjon** [comment]
@clarkperkins I've been adding type hints (to the extent possible, JSON is hard) to all of lowerpines. Could you check if these types match up with what your project expects?

**Comment by clarkperkins** [comment]
Sorry I haven't had a chance to take a look yet - I've been busy this weekend.  I might be able to take a look tomorrow. Thanks for adding all the type hints though, I appreciate it!

**Comment by clarkperkins** [comment]
@Bigfootjon I've noticed just a couple things:

1) It would be helpful to add an empty `py.typed` file in each package, (or corresponding `*.pyi` files) and ensure that they end up in the tar/whl files in order to comply with PEP-561 (https://mypy.readthedocs.io/en/latest/installed_packages.html)
2) The ComplexMessage `__init__` used to be able to take a single MessageAttach object, but now it only takes a list of MessageAttaches or a str, and the docs still show examples of the old behavior.  If this is desired new behavior, that's fine with me!  Just figured I'd point it out.
3) Sort of unrelated, but the dist tar & whl files both contain the `test` package - so you end up with a top level `test` package in your site-packages after installing.

Everything else checked ok in mypy on my project once I added the `py.typed` files!

**Comment by Bigfootjon** [comment]
1. Thanks I’ll read that PEP
2. That’s my mistake, I’ll fix that
3. Also a mistake, I made changes to the setup.py and forgot to exclude test

Thanks for the quick feedback! I appreciate it

**Pull request merged**
